#!/bin/sh

modify_voltage(){
  cd "$rootfs/etc/overclock"
  fex2bin script.fex script.bin
  sntool join uboot.bin
  hakchi flashBoot1 uboot.bin
}

overclock(){

  # TTY0 Color Codes
  Red="\e[33;0;31m"          # Red
  Green="\e[33;0;32m"        # Green
  Yellow="\e[33;0;33m"       # Yellow
  Cyan="\e[33;0;36m"         # Cyan
  White="\e[33;0;37m"        # White
        
  local cpufreq="/sys/devices/system/cpu/cpu0/cpufreq"
  [ -z "$1" ] || cfg_cur_freq="$1"
  local freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
  if ! [ -f "$freq" ]; then
    cfg_cur_freq="max"
    freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
  fi
  cat "$freq" > "$cpufreq/scaling_max_freq"
  echo "current freq: $(cat "$cpufreq/scaling_cur_freq")"
  echo "current temp: $(hwmon)"
}
