#!/bin/sh
# MadMonkey + Swingflip - HakchiResources.com https://discord.gg/8gygsrw

#cat /sys/devices/platform/axp22_board/axp22-regulator.2/regulator/regulator.3/microvolts #Displays current SoC voltage
#cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq #Displays current SoC clock speed
#cat /sys/devices/virtual/thermal/thermal_zone0/temp #Displays SoC core temperature (Safe limit = 90c / Critical = 110c)

printToScreen(){
  echo "$@" > /dev/tty0
}

modify_voltage(){
  [ ! -d "$rootfs/etc/overclock" ] && mkdir -p "$rootfs/etc/overclock" && cd "$rootfs/etc/overclock"
  printToScreen "Grabbing console config..."
  hakchi readBoot1 > uboot.bin 
  sntool split uboot.bin 
  hakchi getScript > script.fex
  printToScreen "Writing new voltage config..."
  sed -i -e 's/LV2_volt = 1460/LV2_volt = 1500/g' script.fex #1.5v max rated voltage for R16 Allwinner
  #You can also set LV2 clock speed here to 1.5ghz but make sure you have adequate cooling 
  printToScreen "Saving and packaging new config..."
  fex2bin script.fex script.bin
  sntool join uboot.bin
  touch "$rootfs/etc/overclock/volt_adjusted"
  printToScreen "Flashing new config and rebooting in 5..." && sleep 1
  printToScreen "4" && sleep 1
  printToScreen "3" && sleep 1
  printToScreen "2" && sleep 1
  printToScreen "1" && sleep 1
  hakchi setScript script.fex
  hakchi flashBoot1 uboot.bin
  reboot
}

overclock(){

  first_install=0

  # TTY0 Color Codes
  Red="\e[33;0;31m"        # Red
  Gre="\e[33;0;32m"        # Green
  Yel="\e[33;0;33m"        # Yellow
  Cya="\e[33;0;36m"        # Cyan
  Whi="\e[33;0;37m"        # White

  if [ ! -f "$rootfs/etc/overclock/volt_adjusted" ]; then
    printToScreen -e "${Gre}**********************************************"
    printToScreen -e "${Gre}******* Hakchi Speed Booster Installer *******"
    printToScreen -e "${Gre}**********************************************"
    printToScreen -e "${Yel} By Swingflip+MadMonkey / HakchiResources.com "
    printToScreen -e "${Gre}**********************************************"
    printToScreen -e "${Cya}Current Hakchi Build: $hakchiVersion          "
    printToScreen -e "${Red}****************${Whi}!!!READ ME!!!${Red}*****************"
    printToScreen -e "${Whi}We do not accept ANY responsibility to any    "
    printToScreen -e "${Whi}damage to your console using this mod! You are"
    printToScreen -e "${Whi}using this at your own risk! Please go to     "
    printToScreen -e "${Whi}https://hakchiresources.com/speedFAQ before   "
    printToScreen -e "${Whi}run this mod install! You have been warned! "
    printToScreen -e "${Red}**********************************************"
    printToScreen -e "${Whi}This installer will install in ${Gre}15 ${Whi}seconds...  "
    sleep 15
    modify_voltage #Edit the voltage config for LV2
  else
    local cpufreq="/sys/devices/system/cpu/cpu0/cpufreq"
    [ -z "$1" ] || cfg_cur_freq="$1"
    local freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
    if ! [ -f "$freq" ]; then
      cfg_cur_freq="max"
      freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
    fi
    cat "$freq" > "$cpufreq/scaling_max_freq"
    printToScreen "Enabling Speed Booster..."
  fi
}
