#!/bin/sh

# MadMonkey + Swingflip - HakchiResources.com https://discord.gg/8gygsrw

modify_voltage(){
  [ ! -d "$rootfs/etc/overclock" ] && mkdir -p "$rootfs/etc/overclock" && cd "$rootfs/etc/overclock"
  echo "Grabbing console config..." > /dev/tty0
  hakchi readBoot1 > uboot.bin 
  sntool split uboot.bin 
  bin2fex script.bin script.fex
  echo "Writing new voltage config..." > /dev/tty0
  sed -i -e 's/LV2_volt = [^"]*/LV2_volt = 1500/g' script.fex #1.5v max rated voltage for R16 Allwinner
  echo "Saving and packaging new config..."
  fex2bin script.fex script.bin
  sntool join uboot.bin
  touch "$rootfs/etc/overclock/volt_adjusted"
  echo "Flashing new config and rebooting in 5..." > /dev/tty0 && sleep 1 && echo "4" > /dev/tty0 && sleep 1 && echo "3" > /dev/tty0 && sleep 1 && echo "2" > /dev/tty0 && sleep 1 && echo "1" > /dev/tty0 && sleep 1
  hakchi flashBoot1 uboot.bin > /dev/tty0 #Pretty sure this reboots...
}

overclock(){

  first_install=0

  # TTY0 Color Codes
  Red="\e[33;0;31m"          # Red
  Green="\e[33;0;32m"        # Green
  Yellow="\e[33;0;33m"       # Yellow
  Cyan="\e[33;0;36m"         # Cyan
  White="\e[33;0;37m"        # White

  if [ ! -f "$rootfs/etc/overclock/volt_adjusted" ]; then
    echo -e "${Green}**********************************************" > /dev/tty0
    echo -e "${Green}******* Hakchi Speed Booster Installer *******" > /dev/tty0
    echo -e "${Green}**********************************************" > /dev/tty0
    echo -e "${Yellow} By MadMonkey+Swingflip / HakchiResources.com " > /dev/tty0
    echo -e "${Green}****************!!!READ ME!!!*****************" > /dev/tty0
    modify_voltage #Edit the voltage config for LV2
  else
    local cpufreq="/sys/devices/system/cpu/cpu0/cpufreq"
    [ -z "$1" ] || cfg_cur_freq="$1"
    local freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
    if ! [ -f "$freq" ]; then
      cfg_cur_freq="max"
      freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
    fi
    cat "$freq" > "$cpufreq/scaling_max_freq"

    modify_voltage

    echo "current freq: $(cat "$cpufreq/scaling_cur_freq")" &> /tmp/script.tmp
    echo "current temp: $(hwmon)" &> /tmp/script.tmp
  fi
}
overclock
